# Generated by Django 2.0.6 on 2018-06-26 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountName', models.CharField(max_length=400)),
                ('budget', models.BigIntegerField()),
                ('resetDate', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('type', models.IntegerField()),
                ('description', models.CharField(max_length=200)),
                ('sum', models.FloatField()),
                ('comments', models.CharField(max_length=400)),
                ('accountID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budgetApp.Accounts')),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Envelopes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('envelopeName', models.CharField(max_length=200)),
                ('envelopeBudget', models.IntegerField()),
                ('currentSum', models.FloatField()),
                ('accountID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budgetApp.Accounts')),
                ('categoryID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budgetApp.Categories')),
            ],
        ),
        migrations.CreateModel(
            name='Permissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permissionName', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduledTransactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('lastUpdate', models.DateField()),
                ('type', models.IntegerField()),
                ('description', models.CharField(max_length=200)),
                ('sum', models.FloatField()),
                ('comments', models.CharField(max_length=400)),
                ('envelopeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budgetApp.Envelopes')),
            ],
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isDefault', models.BooleanField(default=False)),
                ('accountID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budgetApp.Accounts')),
                ('permissionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budgetApp.Permissions')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.EmailField(max_length=254)),
                ('userPass', models.CharField(max_length=200)),
                ('firstName', models.CharField(max_length=200)),
                ('lastName', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='useraccount',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budgetApp.Users'),
        ),
        migrations.AddField(
            model_name='scheduledtransactions',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budgetApp.Users'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='envelopeID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budgetApp.Envelopes'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budgetApp.Users'),
        ),
    ]
