# Generated by Django 2.0.6 on 2018-07-21 20:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('reset_day', models.IntegerField()),
                ('is_inactive', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Envelope',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('budget', models.IntegerField()),
                ('current_sum', models.FloatField()),
                ('is_inactive', models.BooleanField(default=False)),
                ('category', models.IntegerField(choices=[(1, 'Food and Dining'), (2, 'Bills and Utilities'), (3, 'Auto and Transportation'), (4, 'Housing'), (5, 'HealthCare'), (6, 'Savings'), (7, 'Entertainment'), (8, 'Miscellaneous')], default=8)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budgetApp.BudgetAccount')),
            ],
        ),
        migrations.CreateModel(
            name='SavingsHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('saved_sum', models.FloatField()),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budgetApp.BudgetAccount')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduledTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('last_update', models.DateField()),
                ('type', models.IntegerField()),
                ('description', models.CharField(max_length=200)),
                ('sum', models.FloatField()),
                ('comments', models.CharField(max_length=400)),
                ('envelope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budgetApp.Envelope')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=200)),
                ('sum', models.FloatField()),
                ('comments', models.CharField(max_length=400)),
                ('type', models.IntegerField(choices=[(1, 'Expense'), (2, 'Income')], default=1)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budgetApp.BudgetAccount')),
                ('envelope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budgetApp.Envelope')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserBudget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_default', models.BooleanField(default=False)),
                ('permission', models.IntegerField(choices=[(1, 'owner'), (2, 'user'), (3, 'viewer')])),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budgetApp.BudgetAccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
