# Generated by Django 2.0.6 on 2018-06-27 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgetApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ActivityLog',
            new_name='ActivityLogs',
        ),
        migrations.RenameModel(
            old_name='UserAccount',
            new_name='UserAccounts',
        ),
    ]
