# Generated by Django 2.0.6 on 2018-07-22 09:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('budgetApp', '0004_auto_20180722_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetaccount',
            name='last_reset_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
